### PR TITLE
Handle invalid bit width in test vector file

### LINKED ISSUE #502: Test Vector file with invalid bit width throws exception
If a test vector file with an invalid bit width such as `O[2.0]` or `O[[]` is loaded using the Simulate -> Test Vector -> Load Vector button, then logisim throws a java exception. No output is displayed in the Test Vector window and no error dialog is displayed.

My example test vector file with an invalid bit width is:

    A B O[2.0]
    0 0 00
    0 1 01
    1 0 10
    1 1 11

Java exception is:

    Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "2.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.<init>(Integer.java:1111)
	at com.cburch.logisim.data.TestVector$TestVectorReader.parseHeader(TestVector.java:134)
	at com.cburch.logisim.data.TestVector$TestVectorReader.parse(TestVector.java:86)
	at com.cburch.logisim.data.TestVector.<init>(TestVector.java:155)
        at com.cburch.logisim.gui.test.TestFrame$MyListener.actionPerformed(TestFrame.java:197)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)

I am using the `develop` git branch of logisim-evolution.

### PR DESCRIPTION
**Pull request by simoc**
If a `java.lang.NumberFormatException` occurs when parsing a bit width from a test vector file, then display an error dialog with a message like _Test vector in "test2.txt" could not be parsed. Detail: Test Vector header format error: bad width: O[2.0]._

Fixes #502

### CODE REVIEW

File: src/main/java/com/cburch/logisim/data/TestVector.java [hunk 1]
```diff
@@ -131,7 +131,11 @@ private void parseHeader() throws IOException {
             throw new IOException("Test Vector header format error: bad spec: " + t);
 
           columnName[i] = t.substring(0, s);
-          int w = new Integer(t.substring(s + 1, e)).intValue();
```
Comment (maehne) [inline src/main/java/com/cburch/logisim/data/TestVector.java:134]: @BFH-ktt1: Maybe I am wrong, but isn't `Integer`'s value range limited to 32 bits? It seems like this code is not yet adjusted to the maximum bit width of 64 bits.

File: src/main/java/com/cburch/logisim/data/TestVector.java [hunk 2]
```diff
@@ -131,7 +131,11 @@ private void parseHeader() throws IOException {
...
+          int w = 0;
+          try {
+            w = Integer.parseInt(t.substring(s + 1, e));
+          } catch (NumberFormatException ex) {
+          }
 
           if (w < 1 || w > 32)
```
Comment (maehne) [inline src/main/java/com/cburch/logisim/data/TestVector.java:140]: @BFH-ktt1: Isn't the maximum bit width now 64 bits? May be, there are still other places assuming 32 bits.

**Review by maehne — APPROVED** [review]
Looks good to me for merging, but this part of Logisim-evolution's code looks like it needs to be still updated to support 64 bit width.

File: src/main/java/com/cburch/logisim/data/TestVector.java (hunk 2 above)
Comment (BFH-ktt1) [reply src/main/java/com/cburch/logisim/data/TestVector.java:140]: @maehne , correct, however I do not know how up-to-date the test-vector code is in respect to the 64-bit width. I have to look into the details, on my todo list.

Comment (simoc) [reply src/main/java/com/cburch/logisim/data/TestVector.java:140]: I tried changing the `32` here to `64`. The Test Vector file header is parsed correctly, but I then got a different error message, because the 64 bit values are not parsed correctly from the Test Vector file.

I created #507 for those problems.
